
@BASE_URL = http://localhost:3000


### Get API Root Info
GET {{BASE_URL}}/


### Health Check
GET {{BASE_URL}}/health


### Register a new user
POST {{BASE_URL}}/api/auth/register
Content-Type: application/json

{
  "name": "Jonson Carter",       
  "email": "kinih12939@fengnu.com",    
  "password": "12345678" 
}

### Login user
POST {{BASE_URL}}/api/auth/login
Content-Type: application/json

{
  "email": "kinih12939@fengnu.com",     
  "password": "12345678"         
}


### Logout user
POST {{BASE_URL}}/api/auth/logout


### Get current user profile
GET {{BASE_URL}}/api/users/profile


### Create project
POST {{BASE_URL}}/api/projects
Content-Type: application/json

{
    "name": "PicURL",
    "expireAt": "2026-04-31T23:59:59.999Z"
}


### Get all projects
GET {{BASE_URL}}/api/projects


### Get Project
GET {{BASE_URL}}/api/projects/cmnlp61m000004wcpcw71iyiy


### Update project
PATCH {{BASE_URL}}/api/projects/cmnlp61m000004wcpcw71iyiy
Content-Type: application/json

{
    "name": "SnapURL"
}


### Delete Project
DELETE {{BASE_URL}}/api/projects/cmnlo1bo00000axcp0bdc47hd

